import type { CreativePrompt, HabitChallenge } from "../types";

export const CREATIVE: CreativePrompt[] = [
  { id: "dream-house", title: "Draw Your Dream House", icon: "🏠", minAge: 4,
    prompt: "If you could live anywhere, what would your house look like? A treehouse? A house on the moon?",
    tips: ["Start with a big shape for the house", "Add windows and a door", "What is around it — trees, stars, the sea?"] },
  { id: "new-animal", title: "Invent a New Animal", icon: "🦄", minAge: 4,
    prompt: "Mix two animals into one brand-new creature. Give it a name!",
    tips: ["Pick two animals you like", "Mix their body parts", "Where does it live? What does it eat?"] },
  { id: "happy-place", title: "My Happy Place", icon: "🏖️", minAge: 4,
    prompt: "Draw a place that makes you feel calm and happy.",
    tips: ["Think of colors that feel happy", "Who is there with you?", "Add small details you love"] },
  { id: "comic-strip", title: "Three-Box Comic", icon: "💬", minAge: 7,
    prompt: "Draw a tiny comic with a beginning, a middle and an end.",
    tips: ["Box 1: meet your character", "Box 2: something happens", "Box 3: a happy ending"] },
  { id: "music-shaker", title: "Sound Map", icon: "🎵", minAge: 6,
    prompt: "Listen carefully for one minute. Draw every sound you hear as a shape or squiggle.",
    tips: ["Loud sounds = big shapes", "Soft sounds = small dots", "Fast sounds = zig-zags"] },
  { id: "future-city", title: "City of the Future", icon: "🏙️", minAge: 9,
    prompt: "Design a city 100 years from now. How do people travel? How do they keep it green?",
    tips: ["Sketch the main street first", "Add clean energy ideas", "Label your inventions"] },
];

export const HABITS: HabitChallenge[] = [
  { id: "study-table", title: "Organize Your Study Table", icon: "📚", minAge: 5,
    why: "A tidy space helps your brain focus and makes it easy to find things.",
    steps: ["Put pencils and crayons in a cup", "Stack your books neatly", "Throw away scrap paper", "Wipe the table clean"] },
  { id: "toys-away", title: "Put Your Toys Away", icon: "🧸", minAge: 4,
    why: "When toys have a home, they don't get lost or broken.",
    steps: ["Pick up toys from the floor", "Put blocks in their box", "Put teddies on the shelf", "Say “All done!”"] },
  { id: "brush-teeth", title: "Brush Like a Pro", icon: "🪥", minAge: 4,
    why: "Brushing twice a day keeps your teeth strong and your smile bright.",
    steps: ["Put a pea-size bit of toothpaste on the brush", "Brush the fronts, backs and tops", "Brush for 2 minutes (sing a song!)", "Spit and rinse the brush"] },
  { id: "wash-hands", title: "Super Hand Wash", icon: "🧼", minAge: 4,
    why: "Washing hands washes away germs so you stay healthy.",
    steps: ["Wet your hands", "Rub soap on palms, backs and between fingers", "Scrub for 20 seconds", "Rinse and dry"] },
  { id: "drink-water", title: "Water Champion", icon: "💧", minAge: 4,
    why: "Water helps your body and brain work their best.",
    steps: ["Drink a glass of water in the morning", "Drink one with lunch", "Drink one after playing", "Drink one with dinner"] },
  { id: "help-parents", title: "Family Helper", icon: "🤝", minAge: 5,
    why: "Helping at home shows you care and makes jobs faster for everyone.",
    steps: ["Ask a grown-up how you can help", "Set the table or fold socks", "Put your plate in the sink", "Say “Anything else?”"] },
  { id: "kind-words", title: "Kindness Mission", icon: "💛", minAge: 5,
    why: "Kind words make people feel good — and they make you feel good too.",
    steps: ["Say thank you to someone", "Give a friend or family member a compliment", "Share something", "Listen when someone talks"] },
  { id: "make-bed", title: "Make Your Bed", icon: "🛏️", minAge: 6,
    why: "Starting the day with one finished job feels great.",
    steps: ["Straighten the sheet", "Pull up the blanket", "Fluff the pillow", "Place your favorite toy on top"] },
];
