import type { Story } from "../types";
import { mc, order, tf } from "./q";

export const STORIES: Story[] = [
  {
    id: "little-explorer",
    title: "The Little Explorer",
    minAge: 6, maxAge: 8,
    scene: "🧒🔎🌳🐞", sceneColor: "science",
    paragraphs: [
      "Nora loved asking questions. Why do leaves change color? Where do ants go? One sunny morning, she packed a magnifying glass, a notebook and a crunchy apple into her little backpack.",
      "\"Today I am an explorer,\" she told her grandpa. Together they walked to the garden behind their house.",
      "Under a big leaf, Nora found a red ladybug with seven black spots. She counted them slowly — one, two, three, four, five, six, seven! She drew the ladybug in her notebook.",
      "Next, she saw a line of ants carrying tiny crumbs. \"They are working as a team,\" said Grandpa. Nora watched them march all the way to a little hole in the ground.",
      "When the sun began to set, Nora looked at her notebook. It was full of drawings and questions. \"Being an explorer is the best,\" she smiled. \"Tomorrow I will explore the clouds!\"",
    ],
    moral: "Curious eyes can find wonders anywhere — even in your own garden.",
    questions: [
      mc("le-1", "What did Nora pack in her backpack?", ["A magnifying glass, a notebook and an apple", "A ball and a kite", "A pillow and a book"], 0, "She packed tools for exploring — and a snack!"),
      mc("le-2", "How many spots did the ladybug have?", ["Seven", "Three", "Ten"], 0, "Nora counted seven black spots."),
      tf("le-3", "The ants were working as a team.", true, "Yes! Grandpa said the ants were working together."),
      order("le-4", "Put the story in order.", ["Nora packs her bag", "She finds a ladybug", "She watches the ants", "She looks at her notebook"], "That's the order of Nora's adventure."),
      mc("le-5", "What will Nora explore tomorrow?", ["The clouds", "The ocean", "A castle"], 0, "She wants to explore the clouds next!"),
    ],
  },
  {
    id: "pip-the-seed",
    title: "Pip the Brave Little Seed",
    minAge: 4, maxAge: 6,
    scene: "🌰🌱🌧️🌻", sceneColor: "habit",
    paragraphs: [
      "Pip was a tiny seed sleeping in the soft, dark soil.",
      "One day, rain came. Drip, drop, drip! Pip drank the water and felt a little tickle.",
      "Then the warm sun said, \"Good morning, Pip!\" Pip stretched and pushed up, up, up.",
      "A little green sprout popped out of the ground. Day by day, Pip grew taller.",
      "Soon Pip was a big, bright sunflower, smiling at the sky.",
    ],
    moral: "Little by little, we all grow.",
    questions: [
      mc("pip-1", "Where was Pip sleeping?", ["In the soil", "In a tree", "In a cup"], 0, "Seeds sleep in the soil until they grow."),
      tf("pip-2", "Pip drank the rain.", true, "Yes! Seeds need water to grow."),
      mc("pip-3", "What did Pip grow into?", ["A sunflower", "An apple", "A carrot"], 0, "Pip became a big, bright sunflower."),
    ],
  },
  {
    id: "kind-cloud",
    title: "The Kind Little Cloud",
    minAge: 4, maxAge: 7,
    scene: "☁️🌞🌾🐑", sceneColor: "math",
    paragraphs: [
      "Cumulo was a fluffy little cloud who floated over a farm.",
      "Down below, the fields were dry and the flowers looked thirsty.",
      "\"I can help!\" said Cumulo. He puffed up big and let down a soft, gentle rain.",
      "The flowers lifted their heads. The sheep splashed in the puddles. The farmer waved and smiled.",
      "Cumulo felt light and happy. Helping others feels wonderful.",
    ],
    moral: "Helping others makes everyone happier — including you.",
    questions: [
      mc("kc-1", "What was Cumulo?", ["A cloud", "A sheep", "A farmer"], 0, "Cumulo was a fluffy little cloud."),
      mc("kc-2", "How did Cumulo help?", ["He made rain", "He made snow", "He blew the wind"], 0, "He let down gentle rain for the thirsty flowers."),
      tf("kc-3", "Cumulo felt sad after helping.", false, "He felt light and happy!"),
    ],
  },
  {
    id: "moon-garden",
    title: "The Moon Garden",
    minAge: 7, maxAge: 9,
    scene: "🌙🌼🦋✨", sceneColor: "story",
    paragraphs: [
      "Every evening, Arjun and his sister Leela watered the plants on their balcony. But Leela had an idea: \"Let's grow flowers that open at night!\"",
      "They read a library book about moonflowers and evening primroses. These flowers open when the sun goes down and smell sweet to attract night moths.",
      "They planted the seeds in pots and made a chart to track them. Some days nothing happened. Arjun felt impatient, but Leela said, \"Plants take time. Let's keep caring for them.\"",
      "After many weeks, one warm evening, a white flower slowly opened like an umbrella. A soft, fuzzy moth came to visit.",
      "\"Our moon garden!\" whispered Arjun. They drew the flower in their chart and gave it a name: Starlight.",
    ],
    moral: "Patience and care help good things grow.",
    questions: [
      mc("mg-1", "What was special about the flowers?", ["They open at night", "They are blue", "They grow in snow"], 0, "Moonflowers open when the sun goes down."),
      mc("mg-2", "How did the children track their plants?", ["They made a chart", "They took the pots to school", "They asked a robot"], 0, "They kept a chart to see how the plants changed."),
      tf("mg-3", "The flowers opened on the very first night.", false, "It took many weeks — they needed patience."),
      mc("mg-4", "Which animal visited the flower?", ["A moth", "A frog", "A parrot"], 0, "Night flowers smell sweet to attract moths."),
    ],
  },
  {
    id: "recycling-robot",
    title: "Leo's Recycling Robot",
    minAge: 8, maxAge: 11,
    scene: "🤖♻️🧃🌍", sceneColor: "gk",
    paragraphs: [
      "Leo noticed that the bins at his school were always mixed up. Paper, plastic bottles and banana peels were all thrown together.",
      "\"What if a robot could help?\" he wondered. Using cardboard, bottle caps and a lot of tape, he built a friendly robot named Sorty with three doors: blue for paper, yellow for plastic and green for food scraps.",
      "Sorty could not really move, but it had big, clear pictures on each door. Leo made a short poster explaining why sorting matters: recycling saves trees, energy and space in landfills.",
      "At first, only a few classmates used Sorty. Leo did not give up. He asked his teacher if he could explain it at assembly, and he invited everyone to try.",
      "By the end of the month, the school's recycling doubled. The principal gave Sorty a place of honor by the lunch hall. Leo grinned — sometimes a simple idea can make a big difference.",
    ],
    moral: "Small inventions and patient teamwork can help our planet.",
    questions: [
      mc("rr-1", "What problem did Leo notice?", ["The bins were mixed up", "The lunch was cold", "The library was closed"], 0, "Different kinds of waste were all thrown together."),
      mc("rr-2", "Which door was for food scraps?", ["Green", "Blue", "Yellow"], 0, "Green was for food scraps."),
      tf("rr-3", "Leo gave up when only a few classmates used Sorty.", false, "He kept going and explained it at assembly."),
      mc("rr-4", "Why does recycling matter, according to Leo's poster?", ["It saves trees, energy and landfill space", "It makes bins heavier", "It is a fun game only"], 0, "Recycling reuses materials so we use fewer resources."),
      mc("rr-5", "What word best describes Leo?", ["Persistent", "Lazy", "Rude"], 0, "Leo kept trying — that is being persistent."),
    ],
  },
  {
    id: "coral-reef",
    title: "Zara and the Coral Reef",
    minAge: 9, maxAge: 12,
    scene: "🐠🪸🤿🐢", sceneColor: "math",
    paragraphs: [
      "Zara's aunt was a marine biologist, and this summer Zara joined her on a research boat above a coral reef.",
      "Through her snorkel mask, the reef looked like an underwater city. Clownfish darted between anemones, a sea turtle glided past, and parrotfish nibbled on the coral with beak-like teeth.",
      "\"Coral may look like rock,\" her aunt explained, \"but it is made of tiny animals called polyps. They build the reef slowly — only a few centimeters a year.\"",
      "Some coral was pale and white. \"That's coral bleaching,\" said her aunt. \"When the ocean gets too warm, the coral loses the tiny algae that give it food and color.\"",
      "Back on the boat, Zara recorded her observations carefully. She decided to write a report for her class about protecting reefs: using reef-safe sunscreen, reducing plastic and learning about climate. Her aunt smiled: \"Every scientist starts with curiosity.\"",
    ],
    moral: "Understanding nature is the first step to protecting it.",
    questions: [
      mc("cr-1", "What is coral made of?", ["Tiny animals called polyps", "Plastic", "Sand only"], 0, "Coral reefs are built by tiny animals called polyps."),
      mc("cr-2", "What causes coral bleaching?", ["Water that gets too warm", "Too many fish", "Moonlight"], 0, "Warm water makes coral lose its algae."),
      tf("cr-3", "Coral reefs grow very quickly, meters every year.", false, "They grow only a few centimeters a year."),
      mc("cr-4", "Which is one way to help reefs?", ["Use reef-safe sunscreen", "Take coral home", "Throw plastic in the sea"], 0, "Reef-safe sunscreen and less plastic help protect reefs."),
      mc("cr-5", "What does the word 'observations' mean in the story?", ["Things she carefully noticed", "Jokes", "Pictures of her aunt"], 0, "Observations are things you notice by watching closely."),
    ],
  },
  {
    id: "clock-that-forgot",
    title: "The Clock That Forgot to Tick",
    minAge: 9, maxAge: 12,
    scene: "🕰️🔧🧩🏘️", sceneColor: "brain",
    paragraphs: [
      "In the town of Mapleford, the old clock tower stopped at 3:15 one windy Tuesday. People were late for the bus, the bakery opened at the wrong time, and the town band missed practice.",
      "Omar and his friend Priya decided to solve the mystery. They asked the clockkeeper for permission and climbed the tower stairs with a flashlight and a notebook.",
      "Inside, they found gears of every size. Priya noticed one small gear was missing a tooth. \"If one gear stops,\" Omar reasoned, \"every gear connected to it stops too.\"",
      "They sketched the gear and took it to a local workshop. The mechanic showed them how to measure it and make a replacement.",
      "When the new gear clicked into place, the clock began to tick. The whole town cheered at exactly 12:00. Omar and Priya had learned that careful thinking and teamwork can fix almost anything.",
    ],
    moral: "Breaking a big problem into small steps makes it solvable.",
    questions: [
      mc("ct-1", "What time did the clock stop?", ["3:15", "12:00", "7:30"], 0, "It stopped at 3:15 on a windy Tuesday."),
      mc("ct-2", "What was wrong with the clock?", ["A gear was missing a tooth", "The battery died", "A bird built a nest"], 0, "One small gear was broken."),
      tf("ct-3", "The friends asked permission before climbing the tower.", true, "Yes — they asked the clockkeeper first, which is the safe thing to do."),
      mc("ct-4", "Why did the whole clock stop?", ["Connected gears depend on each other", "It was too cold", "Nobody wound it"], 0, "When one gear stops, the gears connected to it stop too."),
    ],
  },
];
